
service: my-awesome-app

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: ${env:AWS_REGION, "eu-west-1"}
  stage: ${opt:stage, "v0"}

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-dotenv-plugin

custom:
  dotenv:
    include: []
  customDomain:
    domainName: ${env:BASE_URL, "test-api.jagetech.com"}
    stage: ${self:provider.stage}
    certificateArn: ${env:CERTIFICATE_ARN}
    endointType: "edge"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
    autoDomainWaitFor: 120
  pythonRequirements:
    dockerizePip: true
    layer:
      name: my-awesome-app-layer
      description: My awesome app layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".venv/**"
        - ".virtualenv/**"
        - "node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}